AWSTemplateFormatVersion: '2010-09-09'
Description: "A stack for creating Elasticsearch service, and connecting it to a log stream"
Resources:
  LambdaStreamToElasticSearch:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: richard-tan-elastic-bucket
        S3Key: streamlambda.js.zip
      Description: Lambda that streams logs to ElasticSearch
      FunctionName: stream-to-elastic-search-again
      Handler: streamlambda.handler
      Role: "arn:aws:iam::250658028269:role/lambda_elasticsearch_execution_antonspike"
      Runtime: "nodejs4.3"
      Environment:
        Variables: {ESENDPOINT: 'search-test123-sij6bfpdgjcoadoqrq6clpktse.ap-southeast-2.es.amazonaws.com'}
