AWSTemplateFormatVersion: '2010-09-09'
Description: "A lambda test"
Parameters:
  ResourcePrefix:
    Type: String
    Description: This prefix will be prepended to the names of all the resources in this stack. Must be lowercase.
    AllowedPattern: "[a-z0-9]+"
    ConstraintDescription: ResourcePrefix parameter can only contain lowercase letters and numbers
  LogGroupName:
    Type: String
    Description: The name of the log Group
Resources:
  LambdaStreamToElasticSearch:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: richard-tan-elastic-bucket
        S3Key: streamlambda.js.zip
      Description: Lambda that streams logs to ElasticSearch
      FunctionName: !Join [ "-", [ {Ref: ResourcePrefix}, stream-to-elastic-search ] ]
      Handler: streamlambda.handler
      Role: !GetAtt LambdaRole.Arn
      Runtime: "nodejs4.3"
      Environment:
        Variables: {
          ESENDPOINT: 'search-rich-elk-elastic-cluster-tgej4aef5oduxz7cwyorvrgopy.ap-southeast-2.es.amazonaws.com',
        }
    DependsOn: 'LambdaRole'
  LambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Principal:
              Service:
                - "lambda.amazonaws.com"
                - !Sub "logs.${AWS::Region}.amazonaws.com"
            Action:
              - "sts:AssumeRole"
            Effect: "Allow"
      Path: "/"
      Policies:
        -
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "es:*"
                  - "logs:*"
                Resource: "*"
  SubsciptionToCloudwatchLogGroup:
    Type: "AWS::Logs::SubscriptionFilter"
    Properties:
      DestinationArn: !GetAtt LambdaStreamToElasticSearch.Arn
      FilterPattern: ''
      LogGroupName: /aws/lambda/BetPublisherSumoFunction-ci
    DependsOn: LambdaPermission
  LambdaPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:*"
      FunctionName: !Ref "LambdaStreamToElasticSearch"
      Principal: !Sub "logs.${AWS::Region}.amazonaws.com"
      SourceArn: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/BetPublisherSumoFunction-ci:*"
    DependsOn: LambdaStreamToElasticSearch
  # LambdaAppLogGroupArnInvokePermission:
  #   Type: AWS::Lambda::Permission
  #   Properties:
  #     FunctionName: !Join [ "-", [ {Ref: ResourcePrefix}, stream-to-elastic-search ] ]
  #     Action: "lambda:InvokeFunction"
  #     Principal: !Sub "logs.${AWS::Region}.amazonaws.com"
  #   DependsOn: LambdaStreamToElasticSearch
